### ISSUE TITLE
Warning: Unknown prop `xsOffset` on <div> tag.

### ISSUE THREAD

**Issue by ckuijjer** [nkt/react-flexgrid#5]
Using the last version 0.7.0 of react-flexgrid shows the following warnings in the console.

```
Warning: Unknown prop `xsOffset` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Col)
    in Col (created by WhatsYourType)
    in div (created by Row)
    in Row (created by WhatsYourType)
    in div (created by Grid)
    in Grid (created by WhatsYourType)
```

This already seems solved in https://github.com/nkt/react-flexgrid/blob/master/src/Col.js#L45 . However I don't see the _passingProps_ in the _Col.js_ installed by npm. Probably it can be solved by bumping the version and publishing it.

**Comment by caiokf-zenefits** [comment]
I am seeing the same issue with other Col props, `xs`, `md` and so on

**Comment by nkt** [comment]
Sorry for so long delay. I've published new release

**Comment by caiokf-zenefits** [comment]
Thank you. I updated to 0.8.0, but I am still seeing:

```
warning.js:39 Warning: Unknown props `xs`, `md` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Col)
    in Col (created by ResourceList)
    in div (created by Row)
    in Row (created by ResourceList)
```

My code looks like:

```
<Grid>
  <Row>
    <Col xs={1} md={4}>
      ...
    </Col>
  </Row>
</Grid>
```

I can provide other details if needed.

**Comment by ckuijjer** [comment]
It's fixed for me in 0.8.0, thanks for the update! 🎉

P.S. @caiokf-zenefits In my case I initially also thought it wasn't solved. Restarting the dev server / webpack solved it for me.

**Comment by caiokf-zenefits** [comment]
Aha! Sorry i missed that. It fixed for me too. Thank you.
